Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,17 +3,33 @@ on:
   push:
     branches:
       - main
+      - dev
+      - test
     
 env:
   PYTHON_VERSION: '3.8'
 
+  
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
-    environment: prod
     steps:
     - name: 'Checkout GitHub Action'
       uses: actions/checkout@v3
+
+    
+    - name: Environment
+      id: set-env
+      run: |
+          if [[ "${{ github.ref_name }}" == "main" ]]; then
+            echo "Deployment to Prod"
+          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "Deployment to Dev"
+          elif [[ "${{ github.ref_name }}" == "test" ]]; then
+            echo "Deployment to Test"
+          else
+            echo "Invalid branch for deployment"
+            exit 1
 
     - name: Install Python
       uses: actions/setup-python@v4
