Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,10 +60,29 @@ jobs:
         # echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
         # chmod 0600 ~/.snowflake/config.toml
 
-        mkdir -p ~/.snowflake
-        cp ./dev/config.toml ~/.snowflake/config.toml
-        echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
-        chmod 0600 ~/.snowflake/config.toml
+
+        if [[ "${{ github.ref_name }}" == "main" ]]; then
+              mkdir -p ~/.snowflake
+              cp ./prod/config.toml ~/.snowflake/config.toml
+              echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+              chmod 0600 ~/.snowflake/config.toml
+              
+        elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+              mkdir -p ~/.snowflake
+              cp ./dev/config.toml ~/.snowflake/config.toml
+              echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+              chmod 0600 ~/.snowflake/config.toml
+              
+        elif [[ "${{ github.ref_name }}" == "test" ]]; then
+              mkdir -p ~/.snowflake
+              cp ./test/config.toml ~/.snowflake/config.toml
+              echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
+              chmod 0600 ~/.snowflake/config.toml
+        else
+              echo "Invalid branch for deployment"
+        exit 1
+        fi
+        
 
     # - name: Test Snowflake Connection
     #   shell: bash
